name: Check Commit Messages

on:
  push:
    branches:
      - master

jobs:
  commit_message_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit messages
        run: |
          # Get the commit message of the latest commit
          commit_message=$(git log --pretty=format:%B -n 1)

          # Extract title, empty line, and content line
          title=$(echo "$commit_message" | head -n 1)
          empty_line=$(echo "$commit_message" | sed -n '/^$/p' | head -n 1)
          content_line=$(echo "$commit_message" | tail -n +3)

          # Check if title is longer than 50 characters
          if [ ${#title} -gt 50 ]; then
            echo "Error: Commit title should not exceed 50 characters."
            exit 1
          fi

          # Check if there is an empty line
          if [ -z "$empty_line" ]; then
            echo "Error: Commit message should contain an empty line after the title."
            exit 1
          fi

          # Check if content line is longer than 50 characters
          if [ ${#content_line} -gt 50 ]; then
            echo "Error: Commit content should not exceed 50 characters per line."
            exit 1
          fi
