name: Flask Tests 

 
on: 
  pull_request: 
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./src/
    
    strategy: 
      matrix:
        python-version: [3.8]
    
    env:
      MODE: "dev"
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: $actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
      - name: Test App Code
        run: python ./test.py
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cache pre-commit hooks
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files